version: '3.7'

services:

  devenv:
    container_name: face-react-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3008:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
